name: Python package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    # Use macOS to support 'say' if your tests do or mock it
    runs-on: macos-latest

    strategy:
      # If you only test Python 3.12, keep it as a single version.
      # If you want more coverage, add them here (e.g. ["3.10", "3.11", "3.12"]).
      matrix:
        python-version: ["3.12"]

    steps:
      # 1) Check out your code from GitHub
      - uses: actions/checkout@v4

      # 2) Set up Python for your matrix version
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Lint + test tools
          pip install flake8 pytest
          # Install your project from setup.py
          pip install .

      - name: Download spaCy model
        run: |
          python -m spacy download en_core_web_sm

      - name: Lint with flake8
        run: |
          # First pass: fail on syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Second pass: treat style warnings as non-fatal
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          pytest
