name: Python package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Lint + test tools
          pip install flake8 pytest
          # Install your project from setup.py
          pip install .
          pip list | grep prosody_say
          python -c "import prosody_say; print(prosody_say.__file__)"

      - name: Download spaCy model
        run: |
          python -m spacy download en_core_web_sm

      - name: Download NLTK resources
        run: |
          python -m nltk.downloader punkt_tab
          python -m nltk.downloader vader_lexicon
          python -m nltk.downloader averaged_perceptron_tagger

      - name: Lint with flake8
        run: |
          # First pass: fail on syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Second pass: treat style warnings as non-fatal
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pwd
          python -c "import sys; print(sys.path)"
          python -m pytest -v
